### ISSUE TITLE
IOException from Graphite Server going Away is not Safely Handled (=> Kills LS)

### ISSUE THREAD

**Issue by original-brownbear** [logstash-plugins/logstash-output-graphite#32]
Seeing this when Graphite goes away:

```sh
[2018-05-25T07:21:31,621][WARN ][logstash.outputs.graphite] Connection to graphite server died {:exception=>#<Errno::EPIPE: Broken pipe - No message available>, :host=>"lrv160ba.europe.intranet", :port=>2003}
[2018-05-25T07:21:31,656][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<SystemCallError: Unknown error (SystemCallError) - No message available>, :backtrace=>["org/jruby/RubyIO.java:1457:in `write'", "org/jruby/RubyIO.java:1428:in `write'", "org/jruby/RubyIO.java:2584:in `write'", "org/jruby/RubyIO.java:2451:in `puts'", "/etc/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/logstash-output-graphite-3.1.3/lib/logstash/outputs/graphite.rb:131:in `receive'", "/etc/logstash-6.0.0/logstash-core/lib/logstash/outputs/base.rb:92:in `block in multi_receive'", "org/jruby/RubyArray.java:1734:in `each'", "/etc/logstash-6.0.0/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "/etc/logstash-6.0.0/logstash-core/lib/logstash/output_delegator_strategies/legacy.rb:22:in `multi_receive'", "/etc/logstash-6.0.0/logstash-core/lib/logstash/output_delegator.rb:49:in `multi_receive'", "/etc/logstash-6.0.0/logstash-core/lib/logstash/pipeline.rb:538:in `block in output_batch'", "org/jruby/RubyHash.java:1343:in `each'", "/etc/logstash-6.0.0/logstash-core/lib/logstash/pipeline.rb:536:in `output_batch'", "/etc/logstash-6.0.0/logstash-core/lib/logstash/pipeline.rb:481:in `worker_loop'", "/etc/logstash-6.0.0/logstash-core/lib/logstash/pipeline.rb:439:in `block in start_workers'"]}
```

=> this plugin isn't safely handling the `IOException` here (as it should) making the pipeline and then LS overall crash.
We need to safely handle this exception and then wait for Graphite to come back up again like we do in e.g. ES output.

**Comment by shanksy01** [comment]
@acchen97 @original-brownbear @monicasarbu what are the thoughts around a patch to the plugin?

**Comment by original-brownbear** [comment]
@jsvd ping ^^

**Comment by jsvd** [comment]
@shanksy01 one potential workaround would be to use the tcp output plugin + the graphite codec which is better at detecting and handling connection loss.

In the meantime we can implement the same [pattern of socket writing we have in the tcp output](https://github.com/logstash-plugins/logstash-output-tcp/blob/master/lib/logstash/outputs/tcp.rb#L152-L160), and be less restrictive in the exceptions we catch.
