### ISSUE TITLE
Windows test failure

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-output-graphite#7]
From https://github.com/elasticsearch/logstash/issues/2487

```
  28) LogStash::Outputs::Graphite if fields_are_metrics => true when metrics_format => ... no match generate no event
     Failure/Error: server.start
     Errno::EADDRINUSE:
       Address already in use - bind - Address already in use: bind
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  29) LogStash::Outputs::Graphite if fields_are_metrics => true when metrics_format => ... match a key with invalid metric_format match the foo key
     Failure/Error: server.start
     Errno::EADDRINUSE:
       Address already in use - bind - Address already in use: bind
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  30) LogStash::Outputs::Graphite if fields_are_metrics => true when metrics_format => ... match all keys match the generated foo key
     Failure/Error: server.start
     Errno::EADDRINUSE:
       Address already in use - bind - Address already in use: bind
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  31) LogStash::Outputs::Graphite if fields_are_metrics => true when metrics_format => ... match all keys match the generated bar key
     Failure/Error: server.start
     Errno::EADDRINUSE:
       Address already in use - bind - Address already in use: bind
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  32) LogStash::Outputs::Graphite if fields_are_metrics => true when metrics_format => ... match one key generate one element
     Failure/Error: server.start
     Errno::EADDRINUSE:
       Address already in use - bind - Address already in use: bind
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  33) LogStash::Outputs::Graphite if fields_are_metrics => true when metrics_format => ... match one key match the generated key
     Failure/Error: server.start
     Errno::EADDRINUSE:
       Address already in use - bind - Address already in use: bind
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  34) LogStash::Outputs::Graphite fields are metrics = false metrics_format not set match one key with metrics list match the custom.foo key
     Failure/Error: server.start
     Errno::EADDRINUSE:
       Address already in use - bind - Address already in use: bind
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  35) LogStash::Outputs::Graphite with a default run generate one element
     Failure/Error: server.start
     Errno::EADDRINUSE:
       Address already in use - bind - Address already in use: bind
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  36) LogStash::Outputs::Graphite with a default run include all metrics
     Failure/Error: server.start
     Errno::EADDRINUSE:
       Address already in use - bind - Address already in use: bind
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'
```

**Comment by ph** [comment]
With the socket patch I now get this error:

``````
................................................................................
................................FFIOError: stream closed
                      close at org/jruby/RubyIO.java:2099
                       stop at C:/Users/Administrator/logstash/vendor/bundle/jru
by/1.9/gems/logstash-output-graphite-0.1.5/spec/support/server.rb:33
                     (root) at C:/Users/Administrator/logstash/vendor/bundle/jru
by/1.9/gems/logstash-output-graphite-0.1.5/spec/outputs/graphite_spec.rb:38
              instance_eval at org/jruby/RubyBasicObject.java:1533
  instance_eval_with_rescue at C:/Users/Administrator/logstash/vendor/bundle/jru
by/1.9/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:471
  instance_eval_with_rescue at C:/Users/Administrator/logstash/vendor/bundle/jru
by/1.9/gems/rspec-core-2.14.8/lib/rspec/core/example.rb:242```
``````

**Comment by ph** [comment]
Will test this again, once the rakelib stuff is fixed in the bundler-move branch.

**Comment by ph** [comment]
fixed in the latest version.
